name: Test npm install

on:
  push:
    branches:
      - master
      - beta
  pull_request:
    branches:
      - master
      - beta

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [11, 12, 14, 16, 18, 'node']

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Verify npm install success
        run: echo "npm install succeeded for Node.js version ${{ matrix.node-version }}"
